Script:
  # 默认使用的脚本语言
  default: JavaScript
  languages:
    # JavaScript 脚本语言
    JavaScript:
      # 是否启用
      enabled: true
      # 使用的脚本引擎 (Nashorn/GraalJS)
      engine: nashorn
    # Kether
    Kether:
      enabled: true
      # 是否启用宽容解析
      tolerance: true
    # Jexl
    Jexl:
      enabled: true
    # Kotlin Scripting
    KotlinScripting:
      enabled: false