Script:
  # 默认使用的脚本语言
  default: JavaScript
  languages:
    # JavaScript 脚本语言
    JavaScript:
      # 是否启用
      enabled: true
      # 使用的脚本引擎 (Nashorn/GraalJS)
      engine: Nashorn
    # Jexl3 脚本
    Jexl:
      enabled: true
    # Kotlin Scripting
    KotlinScripting:
      enabled: false
    # Fluxon
    Fluxon:
      enabled: true
