name: Plugin Test

on:
  workflow_dispatch:
    inputs:
      enable-jfr:
        description: Enable JFR
        required: false
        type: boolean
        default: false
      gradle_args:
        description: Gradle tasks/args to run with
        required: false
        type: string
        default: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Run Gradle Tests
        run: |
          if [ "${{ inputs.enable-jfr }}" = "true" ]; then
            ./gradlew ${{ inputs.gradle_args }} -I .jfr-test.init.gradle.kts
          else
            ./gradlew ${{ inputs.gradle_args }}
          fi
      - name: Upload JFR Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: jfr-${{ github.run_id }}-${{ github.run_attempt }}
          path: outs/jfr/*
          if-no-files-found: ignore
