name: Plugin Test

on:
  workflow_dispatch:
    inputs:
      logging-info:
        description: Info Logging Level
        required: false
        type: boolean
        default: false
      enable-jfr:
        description: Enable JFR
        required: false
        type: boolean
        default: false
      gradle_args:
        description: Gradle tasks/args to run with
        required: false
        type: string
        default: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Run Gradle Tests
        run: |
          ARGS="${{ inputs.gradle_args }}"
          if [ "${{ inputs.enable-jfr }}" = "true" ]; then
            ARGS="$ARGS -I jfr.init.gradle.kts"
          fi
          if [ "${{ inputs.logging-info }}" = "true" ]; then
            ARGS="$ARGS --info"
          fi
          ./gradlew $ARGS
      - name: Upload Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: bench-${{ github.run_id }}-${{ github.run_attempt }}
          path: outs/*
          if-no-files-found: ignore
